site_name: Découverte pratique de la gestion des processus sous Linux
site_description: Activité pédagogique pour comprendre les processus Linux
repo_url: https://github.com/manastria/proclab-unix-docs
repo_name: proclab-unix-docs

extra_css:
    - stylesheets/extra.css
extra_javascript:
    - assets/extra.js
theme:
    name: material
    language: fr
    features:
        - navigation.tabs
        - navigation.sections
        - navigation.indexes
        - navigation.top
        - toc.integrate
        - content.code.copy
    font:
        text: Roboto
        code: Roboto Mono
    palette:
        - scheme: default
          primary: indigo
          accent: indigo
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/brightness-4
              name: Switch to light mode

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.keys
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - admonition
    - pymdownx.details
    - footnotes
    - attr_list
    - def_list
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
    - search:
          lang: fr
nav:
    - Accueil: index.md
    - Installation: installation.md
    - Activités:
          - Introduction: activites/index.md
          - Terminal et processus: activites/terminal.md
          - Gestion Foreground/Background: activites/fg-bg.md
          - Processus zombies: activites/zombie.md
          - Processus orphelins: activites/orphelin.md
          - Priorités: activites/priorites.md
    - Ressources:
          - Processus Unix: ressources/processus.md
          - Signaux: ressources/signaux.md
          - Commandes: ressources/commandes.md
